apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: java
spec:
  replicas: 2
  selector:
    matchLabels:
      type: app
  template:
    metadata:
      labels:
        type: app
    spec:
      containers:
      - name: spring-boot
        image: 148761662695.dkr.ecr.us-east-1.amazonaws.com/java/project-1:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  namespace: java
spec:
  type: LoadBalancer
  selector:
    type: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
