apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: java
spec:
  replicas: 2
  selector:
    matchLabels:
      type: {{ .Values.label.name }}
  template:
    metadata:
      labels:
        type: {{ .Values.label.name}}
    spec:
      containers:
      - name: spring-boot
        image: 148761662695.dkr.ecr.us-east-1.amazonaws.com/java/project-1:1.0
        ports:
        - containerPort: 80
