apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  namespace: java
spec:
  type: LoadBalancer
  selector:
    type: {{ .Values.label.name}}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80